- name: Bootstrap
  hosts: target_hosts
  gather_facts: false
  become: true
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      package:
        name: ['python3', 'python3-pip']

    - name: Configure SSH access for Ansible
      authorized_key:
        user: ansible_user
        key: "{{ lookup('file', '/path/to/ansible_public_key.pub') }}"
        state: present

    - name: Perform initial system configuration
      # Add your tasks here

    - name: Run additional playbooks or roles
      # Include tasks or roles to further configure the system
