- name: Playbook for installing APACHE and PHP module for apache
  hosts: all
  become: true
  tasks:
  
  - name: Ansible apt install apache2 and php module for apache
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: present
      update_cache: yes
