version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: "0"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    restart: unless-stopped